# This file was automatically generated by SWIG (http://www.swig.org).
# Version 3.0.2
#
# Do not make changes to this file unless you know what you are doing--modify
# the SWIG interface file instead.





from sys import version_info
if version_info >= (2,6,0):
    def swig_import_helper():
        from os.path import dirname
        import imp
        fp = None
        try:
            fp, pathname, description = imp.find_module('_polypartition', [dirname(__file__)])
        except ImportError:
            import _polypartition
            return _polypartition
        if fp is not None:
            try:
                _mod = imp.load_module('_polypartition', fp, pathname, description)
            finally:
                fp.close()
            return _mod
    _polypartition = swig_import_helper()
    del swig_import_helper
else:
    import _polypartition
del version_info
try:
    _swig_property = property
except NameError:
    pass # Python < 2.2 doesn't have 'property'.
def _swig_setattr_nondynamic(self,class_type,name,value,static=1):
    if (name == "thisown"): return self.this.own(value)
    if (name == "this"):
        if type(value).__name__ == 'SwigPyObject':
            self.__dict__[name] = value
            return
    method = class_type.__swig_setmethods__.get(name,None)
    if method: return method(self,value)
    if (not static):
        self.__dict__[name] = value
    else:
        raise AttributeError("You cannot add attributes to %s" % self)

def _swig_setattr(self,class_type,name,value):
    return _swig_setattr_nondynamic(self,class_type,name,value,0)

def _swig_getattr(self,class_type,name):
    if (name == "thisown"): return self.this.own()
    method = class_type.__swig_getmethods__.get(name,None)
    if method: return method(self)
    raise AttributeError(name)

def _swig_repr(self):
    try: strthis = "proxy of " + self.this.__repr__()
    except: strthis = ""
    return "<%s.%s; %s >" % (self.__class__.__module__, self.__class__.__name__, strthis,)

try:
    _object = object
    _newclass = 1
except AttributeError:
    class _object : pass
    _newclass = 0


class SwigPyIterator(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, SwigPyIterator, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, SwigPyIterator, name)
    def __init__(self, *args, **kwargs): raise AttributeError("No constructor defined - class is abstract")
    __repr__ = _swig_repr
    __swig_destroy__ = _polypartition.delete_SwigPyIterator
    __del__ = lambda self : None;
    def value(self): return _polypartition.SwigPyIterator_value(self)
    def incr(self, n=1): return _polypartition.SwigPyIterator_incr(self, n)
    def decr(self, n=1): return _polypartition.SwigPyIterator_decr(self, n)
    def distance(self, *args): return _polypartition.SwigPyIterator_distance(self, *args)
    def equal(self, *args): return _polypartition.SwigPyIterator_equal(self, *args)
    def copy(self): return _polypartition.SwigPyIterator_copy(self)
    def next(self): return _polypartition.SwigPyIterator_next(self)
    def __next__(self): return _polypartition.SwigPyIterator___next__(self)
    def previous(self): return _polypartition.SwigPyIterator_previous(self)
    def advance(self, *args): return _polypartition.SwigPyIterator_advance(self, *args)
    def __eq__(self, *args): return _polypartition.SwigPyIterator___eq__(self, *args)
    def __ne__(self, *args): return _polypartition.SwigPyIterator___ne__(self, *args)
    def __iadd__(self, *args): return _polypartition.SwigPyIterator___iadd__(self, *args)
    def __isub__(self, *args): return _polypartition.SwigPyIterator___isub__(self, *args)
    def __add__(self, *args): return _polypartition.SwigPyIterator___add__(self, *args)
    def __sub__(self, *args): return _polypartition.SwigPyIterator___sub__(self, *args)
    def __iter__(self): return self
SwigPyIterator_swigregister = _polypartition.SwigPyIterator_swigregister
SwigPyIterator_swigregister(SwigPyIterator)

class listpoly(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, listpoly, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, listpoly, name)
    __repr__ = _swig_repr
    def iterator(self): return _polypartition.listpoly_iterator(self)
    def __iter__(self): return self.iterator()
    def __nonzero__(self): return _polypartition.listpoly___nonzero__(self)
    def __bool__(self): return _polypartition.listpoly___bool__(self)
    def __len__(self): return _polypartition.listpoly___len__(self)
    def pop(self): return _polypartition.listpoly_pop(self)
    def __getslice__(self, *args): return _polypartition.listpoly___getslice__(self, *args)
    def __setslice__(self, *args): return _polypartition.listpoly___setslice__(self, *args)
    def __delslice__(self, *args): return _polypartition.listpoly___delslice__(self, *args)
    def __delitem__(self, *args): return _polypartition.listpoly___delitem__(self, *args)
    def __getitem__(self, *args): return _polypartition.listpoly___getitem__(self, *args)
    def __setitem__(self, *args): return _polypartition.listpoly___setitem__(self, *args)
    def append(self, *args): return _polypartition.listpoly_append(self, *args)
    def empty(self): return _polypartition.listpoly_empty(self)
    def size(self): return _polypartition.listpoly_size(self)
    def clear(self): return _polypartition.listpoly_clear(self)
    def swap(self, *args): return _polypartition.listpoly_swap(self, *args)
    def get_allocator(self): return _polypartition.listpoly_get_allocator(self)
    def begin(self): return _polypartition.listpoly_begin(self)
    def end(self): return _polypartition.listpoly_end(self)
    def rbegin(self): return _polypartition.listpoly_rbegin(self)
    def rend(self): return _polypartition.listpoly_rend(self)
    def pop_back(self): return _polypartition.listpoly_pop_back(self)
    def erase(self, *args): return _polypartition.listpoly_erase(self, *args)
    def __init__(self, *args): 
        this = _polypartition.new_listpoly(*args)
        try: self.this.append(this)
        except: self.this = this
    def push_back(self, *args): return _polypartition.listpoly_push_back(self, *args)
    def front(self): return _polypartition.listpoly_front(self)
    def back(self): return _polypartition.listpoly_back(self)
    def assign(self, *args): return _polypartition.listpoly_assign(self, *args)
    def resize(self, *args): return _polypartition.listpoly_resize(self, *args)
    def insert(self, *args): return _polypartition.listpoly_insert(self, *args)
    def pop_front(self): return _polypartition.listpoly_pop_front(self)
    def push_front(self, *args): return _polypartition.listpoly_push_front(self, *args)
    def reverse(self): return _polypartition.listpoly_reverse(self)
    __swig_destroy__ = _polypartition.delete_listpoly
    __del__ = lambda self : None;
listpoly_swigregister = _polypartition.listpoly_swigregister
listpoly_swigregister(listpoly)

TPPL_CCW = _polypartition.TPPL_CCW
TPPL_CW = _polypartition.TPPL_CW
class TPPLPoint(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, TPPLPoint, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, TPPLPoint, name)
    __repr__ = _swig_repr
    __swig_setmethods__["x"] = _polypartition.TPPLPoint_x_set
    __swig_getmethods__["x"] = _polypartition.TPPLPoint_x_get
    if _newclass:x = _swig_property(_polypartition.TPPLPoint_x_get, _polypartition.TPPLPoint_x_set)
    __swig_setmethods__["y"] = _polypartition.TPPLPoint_y_set
    __swig_getmethods__["y"] = _polypartition.TPPLPoint_y_get
    if _newclass:y = _swig_property(_polypartition.TPPLPoint_y_get, _polypartition.TPPLPoint_y_set)
    def getX(self): return _polypartition.TPPLPoint_getX(self)
    def getY(self): return _polypartition.TPPLPoint_getY(self)
    def __init__(self): 
        this = _polypartition.new_TPPLPoint()
        try: self.this.append(this)
        except: self.this = this
    __swig_destroy__ = _polypartition.delete_TPPLPoint
    __del__ = lambda self : None;
TPPLPoint_swigregister = _polypartition.TPPLPoint_swigregister
TPPLPoint_swigregister(TPPLPoint)

class TPPLPoly(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, TPPLPoly, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, TPPLPoly, name)
    __repr__ = _swig_repr
    __swig_destroy__ = _polypartition.delete_TPPLPoly
    __del__ = lambda self : None;
    def __init__(self, *args): 
        this = _polypartition.new_TPPLPoly(*args)
        try: self.this.append(this)
        except: self.this = this
    def GetNumPoints(self): return _polypartition.TPPLPoly_GetNumPoints(self)
    def IsHole(self): return _polypartition.TPPLPoly_IsHole(self)
    def SetHole(self, *args): return _polypartition.TPPLPoly_SetHole(self, *args)
    def SetPoint(self, *args): return _polypartition.TPPLPoly_SetPoint(self, *args)
    def GetPoint(self, *args): return _polypartition.TPPLPoly_GetPoint(self, *args)
    def GetPoints(self): return _polypartition.TPPLPoly_GetPoints(self)
    def Clear(self): return _polypartition.TPPLPoly_Clear(self)
    def Init(self, *args): return _polypartition.TPPLPoly_Init(self, *args)
    def Triangle(self, *args): return _polypartition.TPPLPoly_Triangle(self, *args)
    def Invert(self): return _polypartition.TPPLPoly_Invert(self)
    def GetOrientation(self): return _polypartition.TPPLPoly_GetOrientation(self)
    def SetOrientation(self, *args): return _polypartition.TPPLPoly_SetOrientation(self, *args)
TPPLPoly_swigregister = _polypartition.TPPLPoly_swigregister
TPPLPoly_swigregister(TPPLPoly)

class TPPLPartition(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, TPPLPartition, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, TPPLPartition, name)
    __repr__ = _swig_repr
    def RemoveHoles(self, *args): return _polypartition.TPPLPartition_RemoveHoles(self, *args)
    def Triangulate_EC(self, *args): return _polypartition.TPPLPartition_Triangulate_EC(self, *args)
    def Triangulate_OPT(self, *args): return _polypartition.TPPLPartition_Triangulate_OPT(self, *args)
    def Triangulate_MONO(self, *args): return _polypartition.TPPLPartition_Triangulate_MONO(self, *args)
    def MonotonePartition(self, *args): return _polypartition.TPPLPartition_MonotonePartition(self, *args)
    def ConvexPartition_HM(self, *args): return _polypartition.TPPLPartition_ConvexPartition_HM(self, *args)
    def ConvexPartition_OPT(self, *args): return _polypartition.TPPLPartition_ConvexPartition_OPT(self, *args)
    def __init__(self): 
        this = _polypartition.new_TPPLPartition()
        try: self.this.append(this)
        except: self.this = this
    __swig_destroy__ = _polypartition.delete_TPPLPartition
    __del__ = lambda self : None;
TPPLPartition_swigregister = _polypartition.TPPLPartition_swigregister
TPPLPartition_swigregister(TPPLPartition)

# This file is compatible with both classic and new-style classes.


